config/routes.rb
Rails.application.routes.draw do
  resources :trips, only: %i[show]
  resources :waterbodies, only: %i[show index]
  resources :fish do
    collection do
      get 'species'
      get 'locations'
    end
  end
  resources :competitions, only: %i[show index]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'profile/edit', to: 'profile#edit'
  get 'profile', to: 'profile#show'
  get 'profile/:id', to: 'profile#show_other_users_profile', as: 'other_user_profile'
  put 'update_profile/:id', to: 'profile#update', as: 'update_profile'

  devise_for :dadmins, ActiveAdmin::Devise.config

  get 'admin', to: 'admin/dadmins#index'
  ActiveAdmin.routes(self)

  get 'competition/:year', to: 'competitions#show'
  get 'current_competition', to: 'competitions#current_year'
  get 'competition/:year/disputes', to: 'competitions#disputes', as: 'disputes'
  get 'clearance', to: 'clearance_items#index'
  get 'faqs', to: 'questions#index'
  get 'contact', to: 'static#contact'
  get 'about', to: 'static#about'
  get 'choosing-a-kayak', to: 'static#choosing_a_kayak'
  get 'warranty', to: 'static#warranty'
  get 'adventures', to: 'waterbodies#index'
  get 'adventure/:name', to: 'waterbodies#show'
  get 'adventure/:name/:trip_name', to: 'trips#show'

  post 'dispute', to: 'fish#dispute'
  post 'resolve_dispute', to: 'fish#resolve_dispute'
  post 'comment', to: 'fish#comment'
  post 'edit_comment', to: 'fish#edit_comment'

  post 'test_notification', to: 'competitions#notification_test'

  root to: 'static#index'
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :fish

  validates :year, presence: true
  validates :year, numericality: { only_integer: true }
  validates :year, length: { is: 4 }

  def weight_leaders
    fish.not_disputed.order('weight DESC NULLS LAST').limit(10)
  end

  def length_leaders
    fish.not_disputed.order('length DESC NULLS LAST').limit(10)
  end

  def species_leaders
    fish.not_disputed.group(:user_id).select('distinct(species)').count
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authenticate_user!, except: %i[notification_test]
  before_action :setup_show_action, only: %i[show disputes]
  layout 'competition'

  def index
    @competitions = Competition.all
  end

  def show
    @fish = @competition.fish.most_recent.page(params[:page]).per(10)
    @disputes = @competition.fish.disputed
  end

  def current_year
    year = Date.today.year
    redirect_to "/competition/#{year}"
  end

  def disputes
    @fish = @competition.fish.disputed.most_recent.page(params[:page]).per(10)
    if @fish.present?
      render :show
    else
      redirect_to "/competition/#{@competition.year}", notice: 'There are currently no disputed fish'
    end
  end

  def notification_test
    #     app_id = ENV['GK_ONESIGNAL_APP_ID']
    #
    #     params = {
    #       app_id: app_id,
    #       contents: {
    #         en: 'Just a test'
    #       },
    #       ios_badgeType: 'None',
    #       ios_badgeCount: 1,
    #       included_segments: ['All']
    #     }
    #     begin
    #       response = OneSignal::Notification.create(params: params)
    #       notification_id = JSON.parse(response.body)['id']
    #     rescue OneSignal::OneSignalError => e
    #       puts '--- OneSignalError  :'
    #       puts "-- message : #{e.message}"
    #       puts "-- status : #{e.http_status}"
    #       puts "-- body : #{e.http_body}"
    #     end
  end

  private

  def setup_show_action
    @competition = Competition.find_or_create_by(year: params[:year])
    @weight_leaders = @competition.weight_leaders
    @length_leaders = @competition.length_leaders
    @species_leaders = @competition.species_leaders
  end
end

app/views/competitions/_leaders_table.html.erb
<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">Place</th>
      <th scope="col">Name</th>
      <th scope="col">Fish</th>
      <th scope="col"><%= metric.capitalize %></th>
    </tr>
  </thead>
  <tbody>
    <% leaders.each_with_index do |leader, i| %>
      <tr>
        <th scope="row"><%= i + 1 %></th>
        <td><%= link_to competitor(leader.user_id).name, other_user_profile_path(competitor(leader.user_id).to_param) %></td>
        <td><%= leader.species %></td>
        <td>
          <%= leader.send("display_#{metric}".to_sym) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/competitions/_species_leaders_table.html.erb
<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">Place</th>
      <th scope="col">Name</th>
      <th scope="col">Species Count</th>
    </tr>
  </thead>
  <tbody>
    <% leaders.each_with_index do |leader, i| %>
      <tr>
        <th scope="row"><%= i + 1 %></th>
        <td><%= link_to competitor(leader[0]).name, other_user_profile_path(competitor(leader[0].to_param)) %></td>
        <td class="text-center">
          <span class="badge badge-pill badge-secondary"><%= leader[1] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/competitions/index.html.erb
<div class="container">
  <br/>
  <br/>
  <% @competitions.each do |competition| %>
    <%= link_to competition.year, { controller: 'competitions', action: 'show', year: competition.year } %>
  <% end %>
</div>

app/views/competitions/show.html.erb
<div class="container">
  <% if @disputes && @disputes.length > 0 %>
    <%= link_to "Active Disputes <span class='badge badge-light'>#{@disputes.length}</span>".html_safe, disputes_path(Date.today.year), class: 'btn btn-danger' %>
  <% end %>
  <div class="row">
    <div class="col-md-7">
      <br/>
      <h4>Latest Fish Reports</h4>
      <br/>
      <%= paginate @fish, window: 1 %>
      <% @fish.each do |fish| %>
        <%= render partial: 'shared/fish_card', locals: {fish: fish, preview: false} %>
      <% end %>
      <br/>
      <%= paginate @fish, window: 1 %>

      <%= page_entries_info @fish %>
    </div>
    <div class="col-md-5">
      <br/>
      <h4>Leaderboard</h4>
      <br/>
      <div class="leaderboard">
        <h5>Species Leaders</h5>
        <%= render partial: 'species_leaders_table', locals: {leaders: @species_leaders} %>
      </div>
      <div class="leaderboard">
        <h5>Weight Leaders</h5>
        <%= render partial: 'leaders_table', locals: {leaders: @weight_leaders, metric: 'weight'} %>
      </div>
      <div class="leaderboard">
        <h5>Length Leaders</h5>
        <%= render partial: 'leaders_table', locals: {leaders: @length_leaders, metric: 'length'} %>
      </div>
    </div>
  </div>
</div>

<script>
  $('.carousel').carousel({wrap: false});
</script>