config/routes.rb
Rails.application.routes.draw do
  resources :trips, only: %i[show]
  resources :waterbodies, only: %i[show index]
  resources :fish do
    collection do
      get 'species'
      get 'locations'
    end
  end
  resources :competitions, only: %i[show index]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'profile/edit', to: 'profile#edit'
  get 'profile', to: 'profile#show'
  get 'profile/:id', to: 'profile#show_other_users_profile', as: 'other_user_profile'
  put 'update_profile/:id', to: 'profile#update', as: 'update_profile'

  devise_for :dadmins, ActiveAdmin::Devise.config

  get 'admin', to: 'admin/dadmins#index'
  ActiveAdmin.routes(self)

  get 'competition/:year', to: 'competitions#show'
  get 'current_competition', to: 'competitions#current_year'
  get 'competition/:year/disputes', to: 'competitions#disputes', as: 'disputes'
  get 'clearance', to: 'clearance_items#index'
  get 'faqs', to: 'questions#index'
  get 'contact', to: 'static#contact'
  get 'about', to: 'static#about'
  get 'choosing-a-kayak', to: 'static#choosing_a_kayak'
  get 'warranty', to: 'static#warranty'
  get 'adventures', to: 'waterbodies#index'
  get 'adventure/:name', to: 'waterbodies#show'
  get 'adventure/:name/:trip_name', to: 'trips#show'

  post 'dispute', to: 'fish#dispute'
  post 'resolve_dispute', to: 'fish#resolve_dispute'
  post 'comment', to: 'fish#comment'
  post 'edit_comment', to: 'fish#edit_comment'

  post 'test_notification', to: 'competitions#notification_test'

  root to: 'static#index'
end

app/views/shared/_fish_card.html.erb
<div class="card fish-card <%= fish.disputed_by ? 'border-danger' : '' %>">
  <% if fish.disputed_by? %>
    <div class="card-header text-danger">
      <p>
        This fish has been disputed by
        <strong>
          <%= disputed_by(fish.disputed_by) %>
        </strong>
        Resolve the dispute for the fish to be counted.
      </p>
    </div>
  <% end %>
  <div class="card-body">
    <div class="row">
      <div class="col-md-8">
        <% if fish.images %>
          <%= render partial: 'shared/fish_image_carousel', locals: {images: fish.images} %>
        <% end %>
        <br/>
        <p class="card-text"><%= fish.user_comment %></p>
      </div>
      <div class="col-md-4">
        <% if fish.user_image.present? %>
          <%= image_tag(fish.user_image, class: 'img-fluid profile-image') %>
        <% else %>
          <%= image_tag('new/skunk.jpg', class: 'img-fluid profile-image') %>
        <% end %>
        <h5 class="card-title"><%= fish.species %>
          <br/>
          <small class="text-muted">by
            <%= link_to fish.user_name, other_user_profile_path(fish.user_to_param) %></small>
        </h5>
        <p class="card-text">
          <i class="fa fa-arrows-h"></i>
          <%= fish.display_length if fish.length? %>
          <br/>
          <i class="fa fa-balance-scale"></i>
          <%= fish.display_weight if fish.weight? %>
          <br/>
          <i class="fa fa-map-marker"></i>
          <%= fish.location %>
          <br/>
          <i class="fa fa-calendar"></i>
          <%= fish.catch_date.strftime("%-m/%-d/%y") %>
        </p>
        <% unless preview %>
          <%= render partial: 'shared/fish_card_actions', locals: {fish: fish} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% unless preview %>
  <% if fish.comments %>
    <%= render partial: 'shared/fish_comments', locals: {fish: fish} %>
    <div class="clearfix"></div>
  <% end %>
<% end %>

app/views/shared/_fish_card_actions.html.erb
<% unless fish.disputed_by? || fish.user_id == current_user.id %>
  <%= link_to 'Dispute', '#', {:remote => true, 'data-toggle' => "modal", data: {fish_id: fish.id}, 'data-target' => '#dispute-modal', class: 'btn btn-danger btn-sm'} %>
  <%= render partial: 'fish/dispute_form' %>
<% end %>
<% if fish.disputed_by == current_user.id %>
  <%= link_to 'Resolve', '#', {:remote => true, 'data-toggle' => "modal", data: {fish_id: fish.id}, 'data-target' => '#resolve-dispute-modal', class: 'btn btn-success btn-sm'} %>
  <%= render partial: 'fish/resolve_dispute_form' %>
<% end %>
<%= link_to 'Comment', '#', {:remote => true, 'data-toggle' => "modal", data: {fish_id: fish.id}, 'data-target' => '#comment-modal', class: 'btn btn-primary btn-sm'} %>
<%= render partial: 'fish/comment_form' %>
<% if fish.user_id == current_user.id %>
  <%= link_to 'Edit', edit_fish_path(fish), class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/shared/_fish_comments.html.erb
<section class="comments float-right">
  <% fish.comments.each do |comment| %>
    <div class="mt-2 mb-2">
      <div class="row">
        <div class="col-md-2">
          <% user = commenter(comment['user_id']) %>
            <div class="ml-2">
              <% if user.image.present? %>
                <%= image_tag(user.image.thumb.url, class: 'img-fluid commenter-image') %>
              <% else %>
                <%= image_tag('new/skunk.jpg', class: 'img-fluid commenter-image') %>
              <% end %>
            </div>
            <small class="text-muted"></small>
          </div>
          <div class="col-md-10">
            <div class="card comment-card <%= comment_decorator(comment['type']) %>">
              <div class="card-header">
                <strong><%= link_to user.name, other_user_profile_path(user.to_param) %></strong>
                <%= " commented on #{comment_time_formatter(comment['comment_time'])}" %>
                <% if comment_belongs_to_current_user?(comment['user_id']) %>
                  &nbsp;
                  <%= link_to 'Edit', '#', {:remote => true, 'data-toggle' => "modal", data: {fish_id: fish.id, comment: comment.to_json}, 'data-target' => '#edit-comment-modal'} %>
                  <%= render partial: 'fish/edit_comment_form' %>
                <% end %>
              </div>
              <div class="card-body  <%= card_decorator(comment['type']) %>">
                <p class="card-text font-italic">
                  <%= "#{prefix_comment(comment['type'])} #{comment['comment']}" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </section>

app/views/shared/_fish_image_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% images.length.times do |i| %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% images.each_with_index do |image, i| %>
      <div class="carousel-item <%= 'active' if i == 0 %>">
        <img class="d-block img-fluid" src="<%= image.large.url %>" alt="fishie">
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-expanded="false" aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/"><%= image_tag('new/odk_new.png') %></a>
  <div id="navbarSupportedContent" class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto"></ul>
    <ul class="navbar-nav navbar-right">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to "Home<span><br /></span>".html_safe, root_path, { class: "nav-link" } %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(choosing_a_kayak_path) %>">
        <%= link_to "Choosing A Kayak<span>Buying the Best</span>".html_safe, choosing_a_kayak_path, { class: "nav-link" } %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(clearance_path) %>">
        <%= link_to "clearance<span>Great Prices</span>".html_safe, clearance_path, { class: "nav-link" } %>
      </li>
      <li class="nav-item">
        <%= link_to "kayaks<span>Malibu Kayaks</span>".html_safe, 'https://malibukayaks.com/kayaks/', { class: "nav-link", target: "_blank" } %>
      </li>
      <li class="nav-item <%= 'active' if adventure_page? %>">
        <%= link_to "adventures<span>Exploring</span>".html_safe, adventures_path, { class: "nav-link" } %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(faqs_path) %>">
        <%= link_to "faq<span>Help Me!</span>".html_safe, faqs_path, { class: "nav-link" } %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(about_path) %>">
        <%= link_to "about us<span>Old Dominion Kayaks</span>".html_safe, about_path, { class: "nav-link" } %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
        <%= link_to "contact<span>Get In Touch</span>".html_safe, contact_path, { class: "nav-link" } %>
      </li>
      <% if dadmin_signed_in? %>
        <li class="nav-item">
          <%= link_to "admin home", admin_path, { class: "nav-link" } %>
        </li>
        <li>
          <%= link_to "sign out", destroy_dadmin_session_path, {:method => 'delete', class: "nav-link"} %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_section_title.html.erb
<section class="section-title">
  <div class="container">
    <h1>
      <%= h1_main %>
      <small><%= h1_small %></small>
    </h1>
  </div>
</section>