config/routes.rb
Rails.application.routes.draw do
  resources :trips, only: %i[show]
  resources :waterbodies, only: %i[show index]
  resources :fish do
    collection do
      get 'species'
      get 'locations'
    end
  end
  resources :competitions, only: %i[show index]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'profile/edit', to: 'profile#edit'
  get 'profile', to: 'profile#show'
  get 'profile/:id', to: 'profile#show_other_users_profile', as: 'other_user_profile'
  put 'update_profile/:id', to: 'profile#update', as: 'update_profile'

  devise_for :dadmins, ActiveAdmin::Devise.config

  get 'admin', to: 'admin/dadmins#index'
  ActiveAdmin.routes(self)

  get 'competition/:year', to: 'competitions#show'
  get 'current_competition', to: 'competitions#current_year'
  get 'competition/:year/disputes', to: 'competitions#disputes', as: 'disputes'
  get 'clearance', to: 'clearance_items#index'
  get 'faqs', to: 'questions#index'
  get 'contact', to: 'static#contact'
  get 'about', to: 'static#about'
  get 'choosing-a-kayak', to: 'static#choosing_a_kayak'
  get 'warranty', to: 'static#warranty'
  get 'adventures', to: 'waterbodies#index'
  get 'adventure/:name', to: 'waterbodies#show'
  get 'adventure/:name/:trip_name', to: 'trips#show'

  post 'dispute', to: 'fish#dispute'
  post 'resolve_dispute', to: 'fish#resolve_dispute'
  post 'comment', to: 'fish#comment'
  post 'edit_comment', to: 'fish#edit_comment'

  post 'test_notification', to: 'competitions#notification_test'

  root to: 'static#index'
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta content="o2yvyh4-f02towtp0bwa1cku18gbl9-14ytk6u-xa6mp6s-94svxnn5qb75ccn949-7jv-2w6s9766tnor-spe9ddpn6phpy95i3hs90fgkj6z40wfrj6j03wrm3b0mu" name="norton-safeweb-site-verification"/>
    <meta content="malibu kayak dealers, kayaks virginia, kayaks richmond va, gotkayak, old dominion kayaks, james river kayaking, ocean kayaks virginia, fishing kayaks virginia, malibu kayaks virginia" name="keywords"/>
    <meta content="Old Dominion Kayaks serves Virginia, providing demos of our kayaks, so you know before you buy." name="description"/>
    <meta content="GGnZ5igMGveiaarDuV17KPoG6eCdhTi6kFkq+zSUX+o=" name="verify-v1"/>
    <title>Old Dominion Kayaks - Virginia's Fishing Kayak Source</title>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css">

    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body>
    <%= render :partial => 'shared/navigation' %>
    <%= yield %>
    <footer class="footer">
      <div class="container">
        <span class="text-muted">
          <p>
            &copy;
            <%= Date.today.year %>
            Old Dominion Kayaks - All Rights Reserved |
            <%= link_to "home", root_path %>
            &middot;
            <%= link_to "clearance", clearance_path %>
            &middot;
            <%= link_to "kayaks", '#' %>
            &middot;
            <%= link_to "faqs", faqs_path %>
            &middot;
            <%= link_to "contact", contact_path %>
            &middot;
            <%= link_to "warranty", warranty_path %>
          </p>
        </span>
      </div>
    </footer>
    <script>
      new WOW().init();
    </script>
    <% if Rails.env.production? %>
      <!-- Google Analytics -->
      <script>
        (function (i, s, o, g, r, a, m) {
          i['GoogleAnalyticsObject'] = r;
          i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
          },
          i[r].l = 1 * new Date();
          a = s.createElement(o),
          m = s.getElementsByTagName(o)[0];
          a.async = 1;
          a.src = g;
          m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-5452816-1', 'auto');
        ga('send', 'pageview');
      </script>
      <!-- End Google Analytics -->
    <% end %>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta content="o2yvyh4-f02towtp0bwa1cku18gbl9-14ytk6u-xa6mp6s-94svxnn5qb75ccn949-7jv-2w6s9766tnor-spe9ddpn6phpy95i3hs90fgkj6z40wfrj6j03wrm3b0mu" name="norton-safeweb-site-verification"/>
    <meta content="GGnZ5igMGveiaarDuV17KPoG6eCdhTi6kFkq+zSUX+o=" name="verify-v1"/>
    <title>Fishing Competition -
      <%= Date.today.year %>
    </title>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css">

    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <%= stylesheet_link_tag 'authentication', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= button_to('Logout', destroy_user_session_path, method: :delete) %>
    <% end %>
    <% if notice %>
      <div class='alert alert-success'>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class='alert alert-danger'>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
    <footer class="footer">
      <div class="container"></div>
    </footer>
  </body>
</html>

app/views/layouts/competition.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta content="o2yvyh4-f02towtp0bwa1cku18gbl9-14ytk6u-xa6mp6s-94svxnn5qb75ccn949-7jv-2w6s9766tnor-spe9ddpn6phpy95i3hs90fgkj6z40wfrj6j03wrm3b0mu" name="norton-safeweb-site-verification"/>
    <meta content="GGnZ5igMGveiaarDuV17KPoG6eCdhTi6kFkq+zSUX+o=" name="verify-v1"/>
    <title>Fishing Competition -
      <%= Date.today.year %>
    </title>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css">

    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <%= stylesheet_link_tag 'competition', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'competition', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdn.onesignal.com/sdks/OneSignalSDK.js', 'data-turbolinks-track': 'reload' %>
    <script>
      var OneSignal = window.OneSignal || [];
      OneSignal.push(function () {
        OneSignal.init({appId: "c1c1ca78-8cb0-469c-b7ee-b62367e7553b"});
      });
    </script>
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body data-turbolinks="false">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
      <a class="navbar-brand" href="/"><%= image_tag('new/odk_new.png') %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to('Home', "/competition/#{Date.today.year}", class: 'nav-link') %>
          </li>
          <li class="nav-item">
            <%= link_to('Report Fish', new_fish_path, class: 'nav-link') %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to 'Profile', '#', {class: 'nav-link dropdown-toggle', id: 'profile_dropdown', 'data-toggle' => 'dropdown'} %>
            <div class="dropdown-menu" aria-labelledby="profile_dropdown">
              <%= link_to('View', profile_path, class: 'dropdown-item') %>
              <%= link_to('Edit', profile_edit_path, class: 'dropdown-item') %>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-right">
          <li class="nav-item">
            <%= button_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger') %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <div class='alert alert-success'>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class='alert alert-danger'>
          <%= alert %>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <footer class="footer">
      <div class="container">
        <p>You suckers don't stand a chance</p>
      </div>
    </footer>
  </body>
</html>