config/routes.rb
Rails.application.routes.draw do
  resources :trips, only: %i[show]
  resources :waterbodies, only: %i[show index]
  resources :fish do
    collection do
      get 'species'
      get 'locations'
    end
  end
  resources :competitions, only: %i[show index]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'profile/edit', to: 'profile#edit'
  get 'profile', to: 'profile#show'
  get 'profile/:id', to: 'profile#show_other_users_profile', as: 'other_user_profile'
  put 'update_profile/:id', to: 'profile#update', as: 'update_profile'

  devise_for :dadmins, ActiveAdmin::Devise.config

  get 'admin', to: 'admin/dadmins#index'
  ActiveAdmin.routes(self)

  get 'competition/:year', to: 'competitions#show'
  get 'current_competition', to: 'competitions#current_year'
  get 'competition/:year/disputes', to: 'competitions#disputes', as: 'disputes'
  get 'clearance', to: 'clearance_items#index'
  get 'faqs', to: 'questions#index'
  get 'contact', to: 'static#contact'
  get 'about', to: 'static#about'
  get 'choosing-a-kayak', to: 'static#choosing_a_kayak'
  get 'warranty', to: 'static#warranty'
  get 'adventures', to: 'waterbodies#index'
  get 'adventure/:name', to: 'waterbodies#show'
  get 'adventure/:name/:trip_name', to: 'trips#show'

  post 'dispute', to: 'fish#dispute'
  post 'resolve_dispute', to: 'fish#resolve_dispute'
  post 'comment', to: 'fish#comment'
  post 'edit_comment', to: 'fish#edit_comment'

  post 'test_notification', to: 'competitions#notification_test'

  root to: 'static#index'
end

app/models/fish.rb
class Fish < ApplicationRecord
  mount_uploaders :images, ImageUploader

  belongs_to :user
  belongs_to :competition

  validates :species, :location, :catch_date, presence: true
  validates :images, valid_number_of_images: true
  validates :catch_date, valid_catch_date: true
  validates :weight, numericality: { only_integer: true }, if: :weight
  validates :length, numericality: { only_integer: true }, if: :length

  before_validation(on: :create) do
    self.competition_id = Competition.find_by_year(Date.today.year).id
  end

  scope :most_recent, -> { order('created_at DESC') }
  scope :disputed, -> { where('disputed_by is not null') }
  scope :not_disputed, -> { where('disputed_by is null') }

  def user_name
    user.name
  end

  def user_image
    user.image.thumb.url
  end

  def user_to_param
    user.to_param
  end

  def display_weight
    "#{Measured::Weight.new(weight, 'oz').convert_to('lb').format('%.2<value>f')} lbs" if weight
  end

  def display_length
    "#{Measured::Length.new(length, 'in').convert_to('ft').format('%.2<value>f')} feet" if length
  end

  def self.recent_comments_for_notification(days_in_the_past:)
    Fish.all.select(&:comments).collect(&:comments).flatten.select { |comment| comment['comment_time'] >= (Time.now - days_in_the_past.days) }.length
  end

  def self.recent_fish_for_notification(days_in_the_past:)
    Fish.where("created_at > '#{(Time.now - days_in_the_past.days).to_s(:db)}'").count
  end
end

app/controllers/fish_controller.rb
class FishController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :find_fish, only: %i[resolve_dispute dispute comment edit_comment]
  before_action :authorize_user_to_edit, only: %i[edit update]
  before_action :authorize_user_to_dispute, only: %i[dispute]
  before_action :authorize_user_to_resolve_dispute, only: %i[resolve_dispute]
  after_action :notify_users_about_fish, only: %i[create]

  layout 'competition'

  include Notification

  def species
    fish = Fish.order(:species).where('species ilike ?', "%#{params[:term]}%")
    render json: fish.map(&:species).uniq
  end

  def locations
    fish = Fish.order(:location).where('location ilike ?', "%#{params[:term]}%")
    render json: fish.map(&:location).uniq
  end

  def resolve_dispute
    @fish.disputed_by = nil
    add_comment('resolution')
    save_fish_with_comments(notice: 'The dispute has been successfully resolved.', alert: 'The dispute was not resolved. Please try again shortly.')
  end

  def dispute
    @fish.disputed_by = current_user.id
    add_comment('dispute')
    save_fish_with_dispute_comments(notice: "You have successfully disputed #{@fish.user_name}'s #{@fish.species}.", alert: 'The dispute was not successfully created. Please try again shortly.')
  end

  def comment
    add_comment('regular')
    save_fish_with_comments(notice: "Comment added to #{@fish.user_name}'s #{@fish.species}.", alert: 'The comment was not successfully created. Please try again shortly.')
  end

  def edit_comment
    original_comment = JSON.parse(params['original_comment'])
    comment = @fish.comments.select { |comment| comment['comment'] == original_comment['comment'] && comment['user_id'] == original_comment['user_id'] && comment['type'] == original_comment['type'] }
    if comment.empty?
      redirect_to current_competition_path, alert: 'Comment was not updated successfully. Please try again shortly.'
    else
      comment[0]['comment'] = params['new_comment']
      save_fish_with_comments(notice: 'Comment updated successfully', alert: 'Comment was not updated successfully. Please try again shortly.')
    end
  end

  private

  def notify_users_about_fish
    send_notification(segments: ['All Fish'], message: "#{current_user.name} caught a #{@fish.species}!")
  end

  def save_fish_with_dispute_comments(notice:, alert:)
    path = from_disputes? ? dispute_path : current_competition_path
    if @fish.save
      user = User.find(@fish.user_id)
      DisputeMailer.fish_disputed(user, current_user.name, @fish, params[:comment]).deliver_now
      redirect_to path, notice: notice
    else
      redirect_to path, alert: alert
    end
  end

  def save_fish_with_comments(notice:, alert:)
    path = from_disputes? ? dispute_path : current_competition_path
    if @fish.save
      redirect_to path, notice: notice
    else
      redirect_to path, alert: alert
    end
  end

  def from_disputes?
    request.referer.match(/disputes/).present?
  end

  def add_comment(comment_type)
    comment_time = Time.now
    @fish.comments = [] if @fish.comments.nil?
    @fish.comments << { type: comment_type, comment: params[:comment], user_id: current_user.id, comment_time: comment_time }
    send_notification(segments: ['All Comments'], message: "#{current_user.name} commented on #{@fish.user_name}'s #{@fish.species} at #{comment_time.strftime('%l:%M')}")
  end

  def current_year
    Date.today.year
  end

  def current_competition_path
    if params['page'].present? && !params['page'].empty?
      "/competition/#{current_year}?page=#{params['page']}"
    else
      "/competition/#{current_year}"
    end
  end

  def dispute_path
    if params['page'].present? && !params['page'].empty?
      "/competition/#{current_year}/disputes?page=#{params['page']}"
    else
      "/competition/#{current_year}/disputes"
    end
  end

  def find_fish
    @fish = Fish.find(params[:fish_id])
  end

  def authorize_user_to_dispute
    if @fish.user_id == current_user.id
      redirect_to current_competition_path, alert: "You can't dispute your own fish."
    end
  end

  def authorize_user_to_resolve_dispute
    if @fish.disputed_by != current_user.id
      redirect_to current_competition_path, alert: "You can't resolve someone else's dispute."
    end
  end

  def authorize_user_to_edit
    if current_user.id != Fish.find(params[:id]).user_id
      redirect_to current_competition_path, alert: 'You can only edit your own fish.'
    end
  end

  def fish_params
    params.require(:fish).permit(:species, :length, :weight, :location, :water_type, :catch_date, :comment, :disputed_by, :user_comment, :user_id, :competition_id, :remove_images, :images_cache, images: [])
  end
end

app/helpers/fish_helper.rb
module FishHelper
  def disputed_by(user_id)
    User.find(user_id).name
  end
end

app/views/fish/_comment_form.html.erb
<div class="modal fade" id="comment-modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          Leave a comment
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag("/comment", method: "post") do %>
        <%= label_tag(:comment, "Comment:") %>
        <%= text_area_tag(:comment, nil, class: 'form-control') %>
        <%= hidden_field_tag(:fish_id, nil, class: 'comment_fish_id') %>
        <%= hidden_field_tag(:page, params['page']) %>
        <hr/>
        <div class="float-right">
          <%= submit_tag("Comment", class: 'btn btn-primary') %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/fish/_dispute_form.html.erb
<div class="modal fade" id="dispute-modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          Dispute that fish
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag("/dispute", method: "post") do %>
        <%= label_tag(:comment, "Comment:") %>
        <%= text_area_tag(:comment, nil, class: 'form-control') %>
        <%= hidden_field_tag(:fish_id, nil, class: 'comment_fish_id') %>
        <%= hidden_field_tag(:page, params['page']) %>
        <hr/>
        <div class="float-right">
          <%= submit_tag("Open Dispute", class: 'btn btn-primary') %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/fish/_edit_comment_form.html.erb
<div class="modal fade" id="edit-comment-modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <%= "Edit Comment" %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag("/edit_comment", method: "post") do %>
        <%= label_tag(:comment, "Comment:") %>
        <%= text_area_tag(:new_comment, nil, class: 'form-control') %>
        <%= hidden_field_tag(:fish_id, nil, class: 'comment_fish_id') %>
        <%= hidden_field_tag(:page, params['page']) %>
        <%= hidden_field_tag(:original_comment) %>
        <hr/>
        <div class="float-right">
          <%= submit_tag("Edit Comment", class: 'btn btn-primary') %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/fish/_form.html.erb
<%= form_with(model: fish, local: true) do |form| %>
<% if fish.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <h2><%= pluralize(fish.errors.count, "error") %>
      prohibited this fish from being saved:</h2>

    <ul>
      <% fish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :species %>
  <%= form.text_field :species, id: :fish_species, class: 'form-control', placeholder: 'Mutton Snapper, Largemouth Bass, etc.', data: { autocomplete_source: species_fish_index_path } %>
</div>

<div class="form-group">
  <%= form.label :length %>
  <%= form.text_field :length, id: :fish_length, class: 'form-control', placeholder: 'Length (in inches)' %>
</div>

<div class="form-group">
  <%= form.label :weight %>
  <%= form.text_field :weight, id: :fish_weight, class: 'form-control', placeholder: 'Weight (in ounces)' %>
</div>

<div class="form-group">
  <%= form.label :location %>
  <%= form.text_field :location, id: :fish_location, class: 'form-control', placeholder: 'James River, Rudee Inlet, etc.', data: { autocomplete_source: locations_fish_index_path } %>
</div>

<div class="form-group">
  <%= form.label :water_type %>
  <%= form.collection_select :water_type, %w(freshwater saltwater), :to_s, :to_s, {}, {class: 'form-control', id: :fish_water_type} %>
</div>

<div class="form-group">
  <%= form.label :catch_date %>
  <%= form.date_select :catch_date, {}, {id: :fish_catch_date} %>
</div>

<div class="form-group">
  <%= form.label :user_comment, 'Comment' %>
  <%= form.text_area :user_comment, id: :fish_user_comment, class: 'form-control' %>
</div>

<div class="custom-file">
  <%= form.file_field :images, id: :fish_images, multiple: true, class: 'custom-file-input' %>
  <label class="custom-file-label" for="fish_images">Choose Images (Up to 3)</label>
  <%= form.hidden_field :images_cache %>
</div>
<div>
  <label>
    <%= form.check_box :remove_images %>
    Remove images
  </label>
</div>
<%= form.hidden_field :user_id, value: current_user.id %>
<br/>
<br/>
<div class="actions">
  <%= form.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/fish/_resolve_dispute_form.html.erb
<div class="modal fade" id="resolve-dispute-modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          Resolve the dispute
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag("/resolve_dispute", method: "post") do %>
        <%= label_tag(:comment, "Comment:") %>
        <%= text_area_tag(:comment, nil, class: 'form-control') %>
        <%= hidden_field_tag(:fish_id, nil, class: 'comment_fish_id') %>
        <%= hidden_field_tag(:page, params['page']) %>
        <hr/>
        <div class="float-right">
          <%= submit_tag("Resolve Dispute", class: 'btn btn-primary') %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/fish/edit.html.erb
<div class="container">
  <section class="content">
    <h1>Edit Fish</h1>

    <%= render 'form', fish: @fish %>
    <br/>
    <%= link_to 'Show', @fish %>
  </section>
</div>

app/views/fish/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fish</h1>

<table>
  <thead>
    <tr>
      <th>Species</th>
      <th>Length</th>
      <th>Weight</th>
      <th>Location</th>
      <th>Water type</th>
      <th>Catch date</th>
      <th>Comment</th>
      <th>Disputed by</th>
      <th>User comment</th>
      <th>User</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fish.each do |fish| %>
      <tr>
        <td><%= fish.species %></td>
        <td><%= fish.length %></td>
        <td><%= fish.weight %></td>
        <td><%= fish.location %></td>
        <td><%= fish.water_type %></td>
        <td><%= fish.catch_date %></td>
        <td><%= fish.comment %></td>
        <td><%= fish.disputed_by %></td>
        <td><%= fish.user_comment %></td>
        <td><%= fish.user_id %></td>
        <td><%= fish.images %></td>
        <td><%= link_to 'Show', fish %></td>
        <td><%= link_to 'Edit', edit_fish_path(fish) %></td>
        <td><%= link_to 'Destroy', fish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fish', new_fish_path %>

app/views/fish/new.html.erb
<div class="container">
  <section class="content">
    <h1>Report Fish</h1>

    <%= render 'form', fish: @fish %>
  </section>
</div>

app/views/fish/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <%= render partial: 'shared/fish_card', locals: {fish: @fish, preview: true} %>
      <br/>
      <%= link_to 'Edit', edit_fish_path(@fish) if current_user == @fish.user %>
    </div>
  </div>
</div>